-- Short human-friendly code per shift so SMS replies can say "YES 42"
-- instead of quoting a UUID. Postgres backfills identity values for
-- existing rows on ADD COLUMN.

alter table public.shift_requests
  add column if not exists code integer generated by default as identity;

alter table public.shift_requests
  add constraint shift_requests_code_key unique (code);
